---
# group_vars/production.yml
# These variables apply to the PRODUCTION environment.
#
#
# This is a list of all the user accounts, vhosts, databases, etc that should exist on the server.
# The user name will also be used to create a home-folder, a vhost, and a database.
#
# NOTE: usernames are limited to 32 characters

# Syntax and options for vhost entries are documented in the Readme.md file.

GROUPS_LIST:

  - &developers
    name: "developers"
    id: 1001
  - &clients
    name: "clients"
    id: 1002



DEVELOPERS_LIST:

  - &evan
    name: "evan"
    id: 2001
    groups:
      - "developers"
      - "sudo"
    ssh_keys:
      - "evan.pub"
      - "evan_at_eva.pub"
      - "evan_at_home.pub"
      - "evan_at_lonster.pub"

  - &travisci
    name: "travisci"
    id: 2002
    groups:
      - "developers"
      - "sudo"
    ssh_keys:
      - "deploy_rsa.pub"

http:

postfix_settings:
  postfix_domain: 'smirksoftware.com'
  postfix_notify_email: 'evanhsu@gmail.com'
  postfix_use_smtp: true
  postfix_relayhost: 'smtp.mailgun.org'
  postfix_relayhost_user: 'postmaster@mail.smirksoftware.com'
  postfix_relayhost_pass: !vault |
                          $ANSIBLE_VAULT;1.1;AES256
                          61343562393933646531663235356562303762653566343361326635666632643037326361633037
                          3431646162376565653737633338613637303463353031330a643538653136623638383363393733
                          38636561353962643266396266343764333061336165373062383833613966323334646465303336
                          3134396661326135390a333562613034363036346362666439306238376233623833366466363635
                          38643335353635343136326162373363613230363132333838353132643831623763636662633230
                          6464323564376630326232613331666265366139613036383366


CLIENTS_LIST:

  - &smirksoftware
    name: "smirksoftware"
    id: 3001
    groups:
      - "clients"

  - &firecrew
    name: "firecrew"
    id: 3002
    groups:
      - "clients"

  - &natrap
    name: "natrap"
    id: 3004
    groups:
      - "clients"

user_groups:
  - <<: *developers
  - <<: *clients

users:
  - <<: *evan
  - <<: *travisci

  - <<: *smirksoftware

    databases:
      - name: "smirksoftware"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

    nodejs:
      version: 7.5.0
      packages:
        - name: yarn

    vhosts:
      - listen: "80"
        server_name: "smirksoftware.com"
        server_aliases:
          - "www.smirksoftware.com"
        php: true
        root: "/home/smirksoftware/sites/smirksoftware.com/public"


  - <<: *firecrew

    databases:
      - name: "firecrew"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

      - name: "siskiyou_general"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

    nodejs:
      version: 7.5.0
      packages:
        - name: yarn

    vhosts:
      - listen: "443 ssl default"
        ssl: true
        redirect_from_http: true
        server_name: "firecrew.us"
        server_aliases:
          - "firecrew.smirksoftware.com"
        php: true
        root: "/home/firecrew/sites/firecrew.us/public"

    cron: "* * * * * php /home/firecrew/sites/firecrew.us/artisan schedule:run >> /dev/null 2>&1"

  - <<: *natrap

    databases:
      - name: "natrap"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

    nodejs:
      version: 7.5.0
      packages:
        - name: yarn

    vhosts:
      - listen: "80"
        server_name: "natrap.com"
        server_aliases:
          - "www.natrap.com"
        php: true
        root: "/home/natrap/sites/natrap.com/public"

      - listen: "80"
        server_name: "staffing.natrap.com"
        server_aliases:
          - "www.staffing.natrap.com"
        php: true
        root: "/home/natrap/sites/staffing.natrap.com/public"