---
# group_vars/production.yml
# These variables apply to the PRODUCTION environment.
#
#
# This is a list of all the user accounts, vhosts, databases, etc that should exist on the server.
# The user name will also be used to create a home-folder, a vhost, and a database.
#
# NOTE: usernames are limited to 32 characters

# Syntax and options for vhost entries are documented in the Readme.md file.

GROUPS_LIST:

  - &developers
    name: "developers"
    id: 1001
  - &clients
    name: "clients"
    id: 1002



DEVELOPERS_LIST:

  - &evan
    name: "evan"
    id: 2001
    groups:
      - "developers"
      - "sudo"
    ssh_keys:
      - "evan.pub"
      - "evan_at_eva.pub"
      - "evan_at_home.pub"
      - "evan_at_lonster.pub"

  - &travisci
    name: "travisci"
    id: 2002
    groups:
      - "developers"
      - "sudo"
    ssh_keys:
      - "deploy_rsa.pub"

http:

postfix_settings:
  postfix_domain: 'smirksoftware.com'
  postfix_notify_email: 'support@smirksoftware.com'
  postfix_use_smtp: true
  postfix_relayhost: '[smirksoftware.com]'
  postfix_relayhost_user: false
  postfix_relayhost_pass: false


CLIENTS_LIST:

  - &smirksoftware
    name: "smirksoftware"
    id: 3001
    groups:
      - "clients"

  - &firecrew
    name: "firecrew"
    id: 3002
    groups:
      - "clients"

  - &natrap
    name: "natrap"
    id: 3004
    groups:
      - "clients"

user_groups:
  - <<: *developers
  - <<: *clients

users:
  - <<: *evan
  - <<: *travisci

  - <<: *smirksoftware

    databases:
      - name: "smirksoftware"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

    nodejs:
      version: 7.5.0
      packages:
        - name: yarn

    vhosts:
      - listen: "80"
        server_name: "smirksoftware.com"
        server_aliases:
          - "www.smirksoftware.com"
        php: true
        root: "/home/smirksoftware/sites/smirksoftware.com/public"

  - <<: *firecrew

    databases:
      - name: "firecrew"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

      - name: "siskiyou_general"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

    nodejs:
      version: 7.5.0
      packages:
        - name: yarn

    vhosts:
      - listen: "80"
        server_name: "firecrew.us"
        server_aliases:
          - "firecrew.smirksoftware.com"
        php: true
        root: "/home/firecrew/sites/firecrew.us/public"

  - <<: *natrap

    databases:
      - name: "natrap"
        collation: "utf8mb4_unicode_ci"
        encoding: "utf8mb4"

    nodejs:
      version: 7.5.0
      packages:
        - name: yarn

    vhosts:
      - listen: "80"
        server_name: "natrap.com"
        server_aliases:
          - "www.natrap.com"
        php: true
        root: "/home/natrap/sites/natrap.com/public"

      - listen: "80"
        server_name: "staffing.natrap.com"
        server_aliases:
          - "www.staffing.natrap.com"
        php: true
        root: "/home/natrap/sites/staffing.natrap.com/public"